Make adminbot also work if no headers are present
With no headers present, the for loop finished without setting
header_date to any value, causing

UnboundLocalError: local variable 'header_date' referenced before
assignment

Change-Id: I6544c58b0f2c489240d1b43ac3ef572b1cdb34f5